import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { useCreateR21Runner, useDeleteR21Runner, useFreezeR21Runner, useR21Runners } from '@/api/r21';

export default function R21RunnerConfigPage() {
  const list = useR21Runners(); const create = useCreateR21Runner(); const freeze = useFreezeR21Runner(); const remove = useDeleteR21Runner();
  const [name, setName] = useState(''); const [model, setModel] = useState(''); const [effort, setEffort] = useState('medium'); const [timeout, setTimeoutValue] = useState('600');
  return <div className="mx-auto max-w-5xl space-y-6"><div><p className="text-sm text-muted-foreground">r21-codex-cli-single-model-2026-08-v1-8q-60m-15t</p><h1 className="text-3xl font-bold">Codex Runner 配置</h1><p className="mt-2 text-muted-foreground">使用本机已登录的 Codex CLI；不填写、不保存 API Key 或服务 URL。</p></div><Card><CardHeader><CardTitle>新建 Runner</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-4"><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="配置名称" /><Input value={model} onChange={(e) => setModel(e.target.value)} placeholder="Codex model ID" /><Input value={effort} onChange={(e) => setEffort(e.target.value)} placeholder="reasoning effort" /><Input value={timeout} onChange={(e) => setTimeoutValue(e.target.value)} type="number" /><Button disabled={!name || !model || create.isPending} onClick={() => create.mutate({ name, model, reasoning_effort: effort, timeout_seconds: Number(timeout) || 600 }, { onSuccess: () => { setName(''); setModel(''); } })}>创建</Button></CardContent></Card><section className="space-y-3">{(list.data ?? []).map((item) => <Card key={item.id}><CardContent className="flex flex-wrap items-center justify-between gap-3 p-4"><div><strong>{item.name}</strong><p className="font-mono text-xs text-muted-foreground">{item.config_json.model} · {item.config_json.reasoning_effort} · {item.status}</p></div><div className="flex gap-2">{item.status === 'draft' && <Button size="sm" onClick={() => freeze.mutate(item.id)}>冻结并记录 CLI 指纹</Button>}<Button size="sm" variant="destructive" onClick={() => window.confirm('删除此 Runner？') && remove.mutate(item.id)}>删除</Button></div></CardContent></Card>)}</section></div>;
}
